#ifndef GAMEDEF_H
#define GAMEDEF_H


typedef enum GAMEAPI_EVENT
{
 GAMEAPI_EVENT_NO_EVENT  = 0,
 GAMEAPI_EVENT_QUIT = 1,
 GAMEAPI_EVENT_KEY_LEFT = 2,
 GAMEAPI_EVENT_KEY_RIGHT = 3,
 GAMEAPI_EVENT_KEY_UP = 4,
 GAMEAPI_EVENT_KEY_DOWN = 5,


 GAMEAPI_EVENT_MAX_EVENTS = 6
}GAMEAPI_EVENT;


#endif